### ISSUE TITLE
Error : 'norminetter' isn't recognized as an internal or external command

### ISSUE THREAD

**Issue by raphaelbadia** [Kerosene2000/atom-norminette-linter#2]
Hey,  I tried your script but there is an error :

Error: 'norminette' n'est pas reconnu en tant que commande interne
ou externe, un programme ex�cutable ou un fichier de commandes.
    at exit (C:\Users\johhny.atom\packages\norminette-linter\node_modules\atom-linter\lib\helpers.coffee:32:24)
    at triggerExitCallback (C:\Users\johhny\AppData\Local\atom\app-1.0.19\resources\app.asar\src\buffered-process.js:213:47)
    at ChildProcess.<anonymous> (C:\Users\johhny\AppData\Local\atom\app-1.0.19\resources\app.asar\src\buffered-process.js:235:18)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

Any idea on how to fix it ?
Thanks

**Comment by Kerollmops** [comment]
Yeap !!!
If you want to use this linter you'll need to have the `norminette` executable, for example, at 42school it's installed on all the dumps.

I hear that from the staff: "Soon we will open the norminette to everyone of 42, even those not currently being in the school...".
