### ISSUE TITLE
Error: 'norminette' n'est pas reconnu en tant que commande interne ou externe, un programme ex�cutable ou un fichier de commandes

### ISSUE THREAD

**Issue by iruldi** [Kerosene2000/atom-norminette-linter#5]
When I try to save my .c file I've got this issue.

Error: 'norminette' n'est pas reconnu en tant que commande interne
ou externe, un programme ex�cutable ou un fichier de commandes.
    at parameters.exit (C:\Users\user.atom\packages\norminette-linter\node_modules\atom-linter\lib\helpers.js:58:20)
    at triggerExitCallback (C:\Users\user\AppData\Local\atom\app-1.7.4\resources\app.asar\src\buffered-process.js:215:47)
    at ChildProcess.<anonymous> (C:\Users\user\AppData\Local\atom\app-1.7.4\resources\app.asar\src\buffered-process.js:237:18)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

**Comment by Kerollmops** [comment]
You need ton have the `norminette` binary installed on your computer.

**Comment by iruldi** [comment]
Okay but were can we find them ?

**Comment by Kerollmops** [comment]
You need to be a student of the `42 school`, you can ask them sources [on slack/norminette](https://42born2code.slack.com/messages/norminette/).

The `norminette` binary is on all `42 school` computers.
